version: 1.2
workflows:
   - subclass: WDL
     primaryDescriptorPath: /workflows/ncov_workflow.wdl
     testParameterFiles:
     - /workflows/ncov_workflow.json
     name: ncov
     authors:
      - name: Nextstrain
   - subclass: WDL
     primaryDescriptorPath: /workflows/gisaid_ingest.wdl
     testParameterFiles:
     - /workflows/gisaid_ingest.json
     name: gisaid_ingest
     authors:
      - name: Nextstrain
   - subclass: WDL
     primaryDescriptorPath: /workflows/genbank_ingest.wdl
     testParameterFiles:
     - /workflows/genbank_ingest.json
     name: genbank_ingest
     authors:
      - name: Nextstrain
   - subclass: WDL
     primaryDescriptorPath: /workflows/pathogen_workflow.wdl
     testParameterFiles:
     - /workflows/zika_workflow.json
     name: pathogen_build
     authors:
      - name: Nextstrain
   - subclass: WDL
     primaryDescriptorPath: /workflows/zika_workflow.wdl
     testParameterFiles:
     - /workflows/zika_workflow.json
     name: zika_build
     authors:
      - name: Nextstrain
   - subclass: WDL
     primaryDescriptorPath: /workflows/measles_workflow.wdl
     testParameterFiles:
     - /workflows/zika_workflow.json
     name: measles_build
     authors:
      - name: Nextstrain
   - subclass: WDL
     primaryDescriptorPath: /workflows/dengue_workflow.wdl
     testParameterFiles:
     - /workflows/zika_workflow.json
     name: dengue_build
     authors:
      - name: Nextstrain
   - subclass: WDL
     primaryDescriptorPath: /workflows/dengue_ingest.wdl
     testParameterFiles:
     - /workflows/zika_workflow.json
     name: dengue_ingest
     authors:
      - name: Nextstrain
   - subclass: WDL
     primaryDescriptorPath: /workflows/template.wdl
     testParameterFiles:
     - /workflows/template.json
     name: template
     authors:
      - name: Nextstrain
    